CREATE DATABASE IF NOT EXISTS agendasvip;
CREATE DATABASE IF NOT EXISTS tratadorprogramado;
CREATE DATABASE IF NOT EXISTS mpagent;
CREATE DATABASE IF NOT EXISTS deliverywebonline;
CREATE DATABASE IF NOT EXISTS rota6950_cartaovip;
CREATE DATABASE IF NOT EXISTS u348128870_appvendas;
